/** 
DESARROLLAR UN PROGRAMA QUE SUME N VECES UN NUMERO ALEATORIO.
IMPRIMIR EN PANTALLA LOS NUMEROS ALEATORIOS GENERADOS Y LA SUMA OBTENIDA.
LA CANTIDAD DE ITERACIONES DEBERA GENERARSE DE MANERA ALEATORIA, CONSIDERANDO LOS VALORES DEL 1 AL 10.
LOS NUMEROS ALEATORIOS GENERADOS EN CADA ITERACION DEBERAN SER DEL 10 AL 100.
*/
DECLARE
    v_sum NUMBER := 0;
    v_x NUMBER :=0;
    v_num NUMBER;
	v_limit NUMBER;
BEGIN
	v_limit := FLOOR(DBMS_RANDOM.value(1,10));
    LOOP
        v_x := v_x + 1;
        v_num := FLOOR(DBMS_RANDOM.value(10,100));
        DBMS_OUTPUT.PUT_LINE('Número aleatorio '||v_x||' -> '|| v_num);
        v_sum := v_sum + v_num;
    EXIT WHEN v_x = v_limit;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Suma Total = '||v_sum);
END;