/**
CREAR UN PROGRAMA QUE CALCULE LA DISTANCIA DE DOS PUNTOS DE UN PLANO CARTESIANO X,Y.
EL VALOR DE X = (3,2); EL VALOR DE Y = (5,8). MOSTRAR EN PANTALLA LA DISTANCIA DE LOS PUNTOS X,Y.
*/
DECLARE
POINT_X1 NUMBER := 3;
POINT_X2 NUMBER := 2;
POINT_Y1 NUMBER := 5;
POINT_Y2 NUMBER := 8;
DISTANCE DECIMAL(6,2);
BEGIN
DISTANCE := SQRT(POWER((POINT_X1-POINT_X2),2)+POWER((POINT_Y1-POINT_Y2),2));
DBMS_OUTPUT.PUT_LINE('CALCULAR LA DISTANCIA DE DOS PUNTOS');
DBMS_OUTPUT.PUT_LINE('************************************');
DBMS_OUTPUT.PUT_LINE('Punto X : (' || POINT_X1||','||POINT_X2||')');
DBMS_OUTPUT.PUT_LINE('Punto Y : (' || POINT_Y1||','||POINT_Y2||')');
DBMS_OUTPUT.PUT_LINE('Distancia XY : ' || DISTANCE);
END;